@testitem "ChainRules" tags = [:autodiff] begin
    using StatsFuns, Test
    using ChainRulesCore
    using ChainRulesTestUtils
    using Random

    @testset "chainrules" begin
        # `test_frule`/`test_rrule` finite-difference the log-pdfs, which throw `DomainError`
        # outside their domain. ChainRulesTestUtils evaluates the reference at `input ± reach`
        # with `reach = max_range * |tangent|`. With its defaults (`max_range = 1e-2` and, for
        # `Float64`, `|tangent| ≤ 9` since tangents are drawn from `-9:0.01:9`) the reach is at
        # most `0.09`. Drawing every differentiated argument ≥ 0.1 from its boundary therefore
        # keeps the stencil inside the domain by construction (`0.09 < 0.1`), for any draw or
        # seed, so we can rely on the CRTU defaults without a custom `fdm` or tangents. This
        # margin assumes those CRTU defaults; if `max_range` or the tangent range grows, the
        # `0.1` anchor below must grow with it. A fixed seed makes any failure reproducible.
        Random.seed!(1234)
        pos() = 0.1 + randexp()    # positive args (shape/df/rate/λ/eval point)
        unit01() = 0.1 + 0.8rand() # args in [0.1, 0.9): beta `x`, binom `p`

        x = pos()
        y = pos()
        z = unit01()
        test_frule(betalogpdf, x, y, z)
        test_rrule(betalogpdf, x, y, z)

        x = pos()
        y = pos()
        z = pos()
        test_frule(gammalogpdf, x, y, z)
        test_rrule(gammalogpdf, x, y, z)

        x = pos()
        y = pos()
        test_frule(chisqlogpdf, x, y)
        test_rrule(chisqlogpdf, x, y)

        x = pos()
        y = pos()
        z = pos()
        test_frule(fdistlogpdf, x, y, z)
        test_rrule(fdistlogpdf, x, y, z)

        x = pos()
        y = randn()  # location: unbounded
        test_frule(tdistlogpdf, x, y)
        test_rrule(tdistlogpdf, x, y)

        x = rand(1:100)  # `n`: integer, NoTangent
        y = unit01()
        z = rand(1:x)    # `k`: integer, NoTangent
        test_frule(binomlogpdf, x, y, z)
        test_rrule(binomlogpdf, x, y, z)

        x = pos()
        y = rand(1:100)  # `k`: integer, NoTangent
        test_frule(poislogpdf, x, y)
        test_rrule(poislogpdf, x, y)

        # test special case λ = 0
        _, pb = rrule(poislogpdf, 0.0, 0)
        _, x̄1, _ = pb(1)
        @test x̄1 == -1
        _, pb = rrule(poislogpdf, 0.0, 1)
        _, x̄1, _ = pb(1)
        @test x̄1 == Inf

        h = randn()
        a = randn()
        test_frule(owens_t, h, a)
        test_rrule(owens_t, h, a)
    end
end

@testitem "ChainRules fdistlogpdf with small x" tags = [:autodiff] begin
    using StatsFuns, Test
    using ChainRulesTestUtils
    using Random

    # `∂/∂ν1` contains `log(u)`, which used to overflow to `-Inf` for small `x`. The tangent of
    # `x` is scaled to `x` itself, since the default tangent is of order one and its finite
    # differences would leave the domain. Only the `frule` can be tested this way: `test_rrule`
    # differences each argument on its own and ignores the tangents, but both rules are
    # generated by the same `@scalar_rule`.
    Random.seed!(1234)
    @testset "(ν1, ν2, x) = ($ν1, $ν2, $x)" for (ν1, ν2, x) in
        ((3.0, 7.0, 1.0e-308), (1.0, 1.0e18, 1.0e-291))

        test_frule(fdistlogpdf, ν1, ν2, x ⊢ x / 10)
    end
end

@testitem "ChainRules fdistlogpdf with large ν1" setup = [FDistRef] tags = [:autodiff] begin
    using StatsFuns, Test
    using ChainRulesCore
    using SpecialFunctions: digamma

    # `∂/∂x` was a difference of two terms growing like `ν1 / x`, which cancelled completely:
    # at `(1e18, 5, 2)` it returned `0.0`. `test_frule` cannot see this, since a finite
    # difference in `ν1` is lost in the rounding of `ν1` itself, so the pullback is evaluated
    # directly. It returns the three partials separately, whereas `frule` would sum them.
    # The last three are where the single quotient's own `ν1 * ν2` would overflow
    @testset "(ν1, ν2, x) = ($ν1, $ν2, $x)" for (ν1, ν2, x) in (
            (1.0e8, 5.0, 2.0), (1.0e18, 5.0, 2.0), (1.0e20, 1.0, 0.5),
            (4.0, 100.0, floatmax(Float64)),
            (1.0e200, 1.0e300, 1.0e200), (1.0e300, 1.0e200, 2.0), (1.0e200, 1.0e200, 2.0),
        )
        _, pullback = rrule(fdistlogpdf, ν1, ν2, x)
        @test pullback(1.0)[4] ≈ FDistRef.dlogpdf_dx(ν1, ν2, x) rtol = 1.0e-12
    end

    # `(x - 1) / (ν1 * x + ν2)` was `NaN` at `x = Inf`, taking `∂/∂ν1` and `∂/∂ν2` with it
    @testset "x = Inf" begin
        _, pullback = rrule(fdistlogpdf, 3.0, 7.0, Inf)
        _, ∂ν1, ∂ν2, ∂x = pullback(1.0)
        @test ∂ν1 ≈ (digamma(5.0) - digamma(1.5) - 7 / 3) / 2
        @test ∂ν2 == -Inf
        @test ∂x == 0
    end
end
